nav:
 -
   iconClass: 'icon-home'
   name: home
   path: '/'
 -
   iconClass: 'icon-tag'
   name: tags
   path: '/tags'
 -
   iconClass: 'icon-if_archive_archives_'
   name: archives
   path: '/archives'
 -
   iconClass: 'icon-l-about'
   name: about
   path: '/about'
